// ====== Data ported 1:1 from the original LoveSips.html ======

export const REWARD_MESSAGES = {
  25: [
    "One sip closer to me taking care of you, even from this far away.",
    "Every drop you drink makes me smile a little.",
    "You remembered. Good girl. 💜",
    "Hydrated girls are the prettiest girls.",
    "I'm proud of you already, baby.",
    "You deserve to feel your best today.",
    "I can't hand you the glass, so this app will do it for me.",
    "A tiny win... and I'm celebrating it with you.",
    "Thank you for taking care of yourself for me.",
    "I hope you smiled after pressing that button.",
    "You're doing amazing already.",
    "One step closer to today's little victory.",
    "Your body is saying thank you right now.",
    "You listened... that's my girl.",
    "Even from miles away, I'm cheering for every sip.",
    "I love seeing you choose yourself.",
  ],
  50: [
    "Halfway there, just like I knew you'd be.",
    "You never stop making me proud.",
    "My favorite girl is halfway to today's goal.",
    "Imagine me smiling at you right now.",
    "You're doing better than yesterday already.",
    "Half your water... all of my heart.",
    "I wish I could hand you the next glass myself.",
    "You're glowing a little more already.",
    "Don't stop now, beautiful.",
    "You always make small things look adorable.",
    "I noticed your effort, even if nobody else did.",
    "Keep going, princess. You're doing so well.",
    "Your future self will thank you.",
    "You're making me proud one sip at a time.",
    "I adore how you're trying.",
    "Almost there, baby.",
  ],
  75: [
    "Look at you... almost done already.",
    "You're honestly amazing.",
    "I knew you could do it.",
    "So close that I can already celebrate.",
    "Three quarters done. That's my girl.",
    "Keep going, love. Finish strong.",
    "I'm unbelievably proud of you.",
    "Almost a perfect day.",
    "Just one more little push.",
    "I wish I could give you a forehead kiss right now.",
    "You've come too far to stop now.",
    "You make consistency look beautiful.",
    "I hope you know how much I appreciate your effort.",
    "One last stretch, sweetheart.",
    "You've got this, always.",
    "The finish line is waiting for you.",
  ],
  100: [
    "You did it. I'm so incredibly proud of you.",
    "Mission complete, princess. 💜",
    "You kept your promise today.",
    "I wish I could celebrate this with a hug.",
    "You took care of yourself today... thank you.",
    "You reached 100%, just like the way I love you.",
    "My favorite notification of the day.",
    "I hope you're smiling because I definitely am.",
    "You deserve every bit of praise today.",
    "Another perfect day added to your story.",
    "You've made me proud again.",
    "I knew you'd finish it.",
    "You chose yourself today, and that's beautiful.",
    "You're becoming unstoppable.",
    "Today's star belongs to you.",
    "I love you. Now go make tomorrow shine too.",
  ],
};

export const SHOP_ITEMS = {
  tiny: [
    { id: 'nickname', icon: '🏷️', title: 'One Cute Nickname', cost: 20, desc: 'A nickname just for you, chosen by him.' },
    { id: 'compliment', icon: '✨', title: 'Random Compliment', cost: 25, desc: 'One genuine compliment, out of nowhere.' },
    { id: 'thinking_text', icon: '💭', title: '"Thinking of You" Text', cost: 30, desc: 'A text sent just because you crossed his mind.' },
    { id: 'meme', icon: '😂', title: 'One Meme', cost: 20, desc: 'A meme picked specifically for you.' },
    { id: 'song_rec', icon: '🎵', title: 'Song Recommendation', cost: 30, desc: "A song he thinks you'll love." },
    { id: 'virt_kiss', icon: '😘', title: 'Virtual Forehead Kiss', cost: 35, desc: 'A forehead kiss, sent through the screen.' },
    { id: 'miss_you_para', icon: '🥺', title: '"I Miss You" Paragraph', cost: 40, desc: 'A paragraph when the distance feels too much.' },
    { id: 'goodnight_para', icon: '🌙', title: 'Goodnight Paragraph', cost: 45, desc: 'Something beautiful to fall asleep to.' },
    { id: 'goodmorning_para', icon: '☀️', title: 'Good Morning Paragraph', cost: 50, desc: 'Words waiting for you when you wake up.' },
  ],
  sweet: [
    { id: 'kiss', icon: '💋', title: 'Kiss', cost: 70, desc: 'One kiss, redeemable in person.' },
    { id: 'hug', icon: '🤗', title: 'Hug', cost: 80, desc: 'A real hug, whenever you cash it in.' },
    { id: 'voice_note', icon: '🎙️', title: 'Voice Note', cost: 90, desc: 'A voice message so you can hear his voice.' },
    { id: 'selfie', icon: '📸', title: 'Cute Selfie', cost: 85, desc: 'A selfie sent just for you.' },
    { id: 'love_letter', icon: '💌', title: 'Love Letter', cost: 120, desc: 'A handwritten letter, just for you.' },
    { id: 'mini_story', icon: '📖', title: 'Mini Story About Us', cost: 130, desc: 'A short story about your relationship, written by him.' },
    { id: 'why_i_love_you', icon: '📝', title: '"Why I Love You" List', cost: 110, desc: '5 reasons, handpicked and honest.' },
    { id: 'reel_dedicated', icon: '📹', title: 'Reel Dedicated To You', cost: 100, desc: 'A reel made or picked just for you.' },
    { id: 'matching_wallpaper', icon: '📱', title: 'Matching Wallpaper', cost: 95, desc: 'A wallpaper you both use.' },
    { id: 'surprise_audio', icon: '🎤', title: 'Surprise Audio Message', cost: 150, desc: 'An unplanned audio message, raw and sweet.' },
  ],
  premium: [
    { id: 'call_30', icon: '📞', title: '30 Minute Call', cost: 200, desc: '30 minutes, just us, on the phone.' },
    { id: 'choc_date', icon: '🍫', title: 'Chocolate Date', cost: 250, desc: 'A date with chocolate involved.' },
    { id: 'icecream_date', icon: '🍦', title: 'Ice Cream Date', cost: 220, desc: 'Ice cream, together.' },
    { id: 'pizza_date', icon: '🍕', title: 'Pizza Date', cost: 230, desc: 'Pizza and good company.' },
    { id: 'cafe_date', icon: '☕', title: 'Café Date', cost: 240, desc: 'A slow café morning, just you two.' },
    { id: 'arcade_date', icon: '🕹️', title: 'Arcade Date', cost: 260, desc: 'Games, laughs, and a little competition.' },
    { id: 'movie_night', icon: '🎬', title: 'Movie Night', cost: 300, desc: 'A whole night, just the two of you.' },
    { id: 'cook_together', icon: '🍳', title: 'Cook Together', cost: 280, desc: 'Making something from scratch, together.' },
    { id: 'online_game_date', icon: '🎮', title: 'Online Game Date', cost: 220, desc: 'A gaming session, just you two.' },
    { id: 'sunset_date', icon: '🌇', title: 'Watch Sunset Together', cost: 250, desc: 'Sitting somewhere beautiful, watching the sky.' },
    { id: 'playlist', icon: '🎧', title: 'Playlist Made For You', cost: 300, desc: 'A playlist curated specifically for you.' },
  ],
  legendary: [
    { id: 'whole_day_date', icon: '🌟', title: 'Whole Day Date', cost: 1000, desc: 'An entire day, just for you.' },
    { id: 'surprise_gift', icon: '🎁', title: 'Surprise Gift', cost: 1500, desc: 'Something special, picked just for you.' },
    { id: 'plushie', icon: '🧸', title: 'Plushie', cost: 1200, desc: 'A soft one, from him to you.' },
    { id: 'polaroid', icon: '📷', title: 'Polaroid Picture', cost: 1100, desc: 'A moment, printed and kept forever.' },
    { id: 'hoodie_steal', icon: '🧥', title: 'Hoodie Steal Coupon 😂', cost: 800, desc: 'One guilt-free hoodie steal, officially approved.' },
    { id: 'matching_bracelet', icon: '📿', title: 'Matching Bracelet', cost: 2000, desc: 'Something you both wear.' },
    { id: 'candlelight_dinner', icon: '🕯️', title: 'Candlelight Dinner', cost: 2500, desc: 'The full experience. Just you two.' },
    { id: 'handwritten_letter', icon: '✉️', title: 'Handwritten Letter (Mailed)', cost: 1800, desc: 'Written by hand, sent to your door.' },
  ],
};

export const MYSTERY_BOX_COST = 1000;

// Weighted rarity tiers: common 60%, rare 28%, epic 9%, legendary 3%
export const MYSTERY_POOL = [
  { w: 8, type: 'hearts', amount: 20, icon: '❤️', title: '+20 Hearts Bonus', desc: 'A little bonus love, just like that.' },
  { w: 8, type: 'item', id: 'compliment', icon: '✨', title: 'Random Compliment', desc: 'One genuine compliment, out of nowhere.' },
  { w: 8, type: 'item', id: 'meme', icon: '😂', title: 'One Meme', desc: 'A meme picked specifically for you.' },
  { w: 8, type: 'item', id: 'song_rec', icon: '🎵', title: 'Song Recommendation', desc: "A song he thinks you'll love." },
  { w: 8, type: 'item', id: 'selfie', icon: '📸', title: 'Cute Selfie', desc: 'A selfie sent just for you.' },
  { w: 8, type: 'item', id: 'love_letter', icon: '💌', title: 'Love Letter', desc: 'A handwritten letter, just for you.' },
  { w: 5, type: 'hearts', amount: 50, icon: '❤️', title: '+50 Hearts Bonus', desc: 'Bonus hearts for the lucky one.' },
  { w: 5, type: 'item', id: 'voice_note', icon: '🎙️', title: 'Voice Note', desc: 'A voice message so you can hear his voice.' },
  { w: 5, type: 'item', id: 'choc_date', icon: '🍫', title: 'Chocolate Date', desc: 'A date with chocolate involved.' },
  { w: 5, type: 'item', id: 'movie_night', icon: '🎬', title: 'Movie Night', desc: 'A whole night, just the two of you.' },
  { w: 4, type: 'item', id: 'call_30', icon: '📞', title: '30 Minute Call', desc: '30 minutes, just us, on the phone.' },
  { w: 4, type: 'item', id: 'song_dedicated', icon: '🎶', title: 'Song Dedication', desc: 'A song dedicated publicly to you.' },
  { w: 3, type: 'hearts', amount: 150, icon: '❤️', title: '+150 Hearts Bonus', desc: 'A big heart drop — you deserved it.' },
  { w: 3, type: 'item', id: 'surprise_gift', icon: '🎁', title: 'Surprise Gift', desc: 'Something special, picked just for you.' },
  { w: 2, type: 'item', id: 'whole_day_date', icon: '🌟', title: 'Whole Day Date', desc: 'An entire day, just for you.' },
  { w: 1, type: 'special', id: 'double_rewards', icon: '💫', title: 'Double Rewards (3 Days)', desc: 'Every heart earned doubles for the next 3 days.' },
  { w: 2, type: 'hearts', amount: 500, icon: '❤️', title: '+500 Hearts Bonus', desc: 'Jackpot! A massive heart reward.' },
  { w: 3, type: 'golden_ticket', icon: '🎫', title: 'Golden Ticket', desc: 'Use it to buy any one reward for free.' },
];

export const DAILY_GIFT_AMOUNT = 25;

export const ACHIEVEMENTS = [
  { id: 'first_sip', icon: '💧', title: 'First Sip', desc: 'Log your first drink.' },
  { id: 'fresh_start', icon: '🌱', title: 'Fresh Start', desc: 'Reach 25% once.' },
  { id: 'half_tide', icon: '🌊', title: 'Half Tide', desc: 'Reach 50%.' },
  { id: 'almost_there', icon: '⭐', title: 'Almost There', desc: 'Reach 75%.' },
  { id: 'perfect_day', icon: '👑', title: 'Perfect Day', desc: 'Complete 100%.' },
  { id: 'double_victory', icon: '🚀', title: 'Double Victory', desc: 'Complete goal 2 days in a row.' },
  { id: 'flame_7', icon: '🔥', title: 'Little Angel', desc: '7-day streak.' },
  { id: 'moon_walker', icon: '🌙', title: 'Sweetheart 💕', desc: '14-day streak.' },
  { id: 'my_good_girl', icon: '☄️', title: 'My Good Girl', desc: '30-day streak.' },
  { id: 'my_haven', icon: '🌌', title: 'My Haven', desc: '60-day streak.' },
  { id: 'hydration_queen', icon: '💙', title: 'Hydration Queen', desc: '100-day streak.' },
  { id: 'supernova', icon: '🌸', title: 'Extra Love 🌸', desc: 'Drink 500ml above goal.' },
  { id: 'queen_of_my_heart', icon: '👸', title: 'Queen of My Heart', desc: 'Complete your goal all 7 days of a week.' },
  { id: 'wifey', icon: '💍', title: 'Wifey 💍', desc: 'Never miss a single day — complete every day in a month.' },
  { id: 'my_babygirl', icon: '🎯', title: 'Heart Keeper 💗', desc: 'Hit goal 5 times in one week.' },
  { id: 'loved_beyond', icon: '❤️', title: 'Loved Beyond Measure', desc: 'Unlock every other achievement.' },
];

export const MILESTONE_HEART_VALUES = { 25: 10, 50: 15, 75: 20, 100: 30 };
export const DAILY_COMPLETION_BONUS = 25;
export const STREAK7_BONUS = 100;
export const PERFECT_WEEK_BONUS = 250;
